import { definePlugin } from "@barodoc/core";

export interface SearchPluginOptions {
  /**
   * Enable/disable search
   * @default true
   */
  enabled?: boolean;

  /**
   * Pagefind options
   */
  pagefind?: {
    /**
     * Base URL for search
     */
    baseUrl?: string;

    /**
     * Exclude patterns
     */
    exclude?: string[];
  };
}

export default definePlugin<SearchPluginOptions>((options = {}) => {
  const { enabled = true } = options;

  return {
    name: "@barodoc/plugin-search",

    hooks: {
      "config:loaded": (config, context) => {
        // Update config to enable/disable search
        return {
          ...config,
          search: {
            ...config.search,
            enabled,
          },
        };
      },

      "build:done": async (buildContext, context) => {
        if (!enabled) return;

        // Pagefind is run separately by the CLI
        // This hook can be used for additional processing
        console.log("Search index will be generated by pagefind");
      },
    },
  };
});
